# Linear Algebra

## Aims

Demonstrate Linear Algebra concepts using:
- Python
- Numpy
- Matplotlib/Seaborn

## Books

https://gwthomas.github.io/docs/math4ml.pdf

http://cs229.stanford.edu/section/cs229-prob.pdf

https://www.deeplearningbook.org/contents/linear_algebra.html

https://web.stanford.edu/~boyd/vmls/vmls.pdf

(What I've started with)<br>
https://mml-book.github.io/book/mml-book.pdf

## What is Linear Algebra?

Linear Algebra is a branch of mathematics that's used in statistics and therefore, Data Science.
The type of Linear Algebra used in Data Science are Matrices and Vectors. <br>

It's called Linear because of the *Linear combinations*, ie, using arithmetic on columns of numbers (vectors) <br>
and arrays of numbers (matrices) to create new columns and arrays of numbers.

Linear Algebra is used for analysing: <br>
- lines and planes
- vector spaces
- mappings
Which are used for linear transforms.<br>

An example of a simple linear equation is below:

In [ ]:
y = 5 * x + 9

## Linear Algebra and Statistics

[Linear Algebra](https://machinelearningmastery.com/gentle-introduction-linear-algebra/) is used in Statistics for the following methods:
- Vector and matrix notation, especially multivariate statistics
- Solutions to least squares and weighted least squares, for linear regression.
- Estimates of mean and variance of data matrices
- Covariance matrix that is used in multinomial Gaussian distributions
- Principal Component Analysis for data reduction.

### What is a Scalar?

A [scalar](https://softwareengineering.stackexchange.com/questions/238033/what-does-it-mean-when-data-is-scalar#:~:text=A%20scalar%20is%20a%20simple%20single%20numeric%20value,that%20contains%20more%20than%20one%20single%20numeric%20value.) is a simple numeric value like:
-3
-2/3
-4.55563

Scalars are usually integers, fixed point or floating-point numbers, <br>
as opposed to an array or object.

### What is a Vector?

A vector is a tuple of one or more scalars. <br>

In Python, a [tuple](https://www.w3schools.com/python/python_tuples.asp) is a collection which is ordered and **unchangeable**.

Vectors are often represented using a lowercase character such as 'v':

In [ ]:
# v1, v2, v3 are scalar, often real values.
v = (v1, v2, v3)

### Defining a Vector

A vector can be defined in Python as a numpy array.<br>
A numpy array can be created from a list of numbers.<br>
Below, the vector is defined as having length 3 and <br>
integer values 1, 2, 3.

In [4]:
# Create a vector
import numpy as np

v = np.array([1, 2, 3])
print(v)

[1 2 3]


### Vector Multiplication

Two vectors of equal length can be multiplied together:

In [ ]:
c = a * b

Just like addition and subtraction, this is performed element-wise to<br>
result in a new vector *with the same length*.

In [ ]:
a * b = (a1 * b1, a2 * b2, a3 * b3)

This is what it looks like in numpy:

In [5]:
# multiply vectors
from numpy import array

# Define the first vector 
a = array([1, 2, 3])
print(a)

# Define the second vector
b = array([1, 2, 3])
print(b)

# Multiply the two vectors together
c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


### Vector addition

In [6]:
# add vectors

# Define the first vector 
a = array([1, 2, 3])
print(a)

# Define the second vector
b = array([1, 2, 3])
print(b)

# Add the two vectors together
c = a + b
print(c)

[1 2 3]
[1 2 3]
[2 4 6]


### Vector division

In [8]:
# divide vectors

# Define the first vector 
a = array([1, 2, 3])
print(a)

# Define the second vector
b = array([1, 2, 3])
print(b)

# Divide the two vectors together
c = a // b
print(c)

[1 2 3]
[1 2 3]
[1 1 1]


### Vector subtraction

In [9]:
# subtract vectors

# Define the first vector 
a = array([1, 2, 3])
print(a)

# Define the second vector
b = array([1, 2, 3])
print(b)

# subtract the two vectors together
c = a - b
print(c)

[1 2 3]
[1 2 3]
[0 0 0]


### Vector dot product

If:
c = a * b, and <br>
a * b = (a1 * b1, a2 * b2, a3 * b3)<br>

Then for the dot product:<br>
d = a$\cdot$b
a$\cdot$b = (a1 * b1 + a2 * b2 + a3 * b3)<br>

This can be calculated quickly using the *numpy.dot()* function.

In [10]:
# dot product vectors
from numpy import array

# Define the first vector 
a = array([1, 2, 3])
print(a)

# Define the second vector
b = array([1, 2, 3])
print(b)

# calculate the dot pro
c = np.dot(a, b)
print(c)

[1 2 3]
[1 2 3]
14


## Matrices

### What is a Matrix?

A matrix is a two-dimensional array of scalars with one or more columns and one or more rows.<br>

The notation for a matrix is often an uppercase letter, and entries are referred to by their<br>
two-dimensional subscript of row(i) and column(j), such as a<sub>ij</sub>

In [ ]:
# Example of a matrix referred to by rows and columns.
A = ((a11, a12), (a21, a22), (a31, a32))

### Defining a Matrix

A matrix can be defined in Python using a 2d NumPy array.<br>

A NumPy array can be constructed using a list of lists.<br>
In the example below, the array has 2 rows and 3 columns.

In [11]:
# create matrix
A = array([[1, 2, 3],[4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


### Matrix Addition

Two matrices **with the same dimensions** can be added together to create a third new matrix.

In [ ]:
C = A + B

The scalar elements in the resulting matrix are calculated<br> 
as the addition of the elements in each of the matrices being added

This can be implemented in NumPy using with the plus operator<br>
on two NumPy arrays.

In [15]:
# Add two matrices
A = array([[1, 2, 3], [4, 5, 6]])
print(f'The matrice for A: \n{A}')
B = array([[1, 2, 3], [4, 5, 6]])
print(f'\nThe matrice for B: \n{B}')

# Add the matrices together
C = A + B
print(f'The two matrices added together: \n{C}')

The matrice for A: 
[[1 2 3]
 [4 5 6]]

The matrice for B: 
[[1 2 3]
 [4 5 6]]
The two matrices added together: 
[[ 2  4  6]
 [ 8 10 12]]


### Matrix Dot Product

Also called matrix multiplication, the matrix dot product<br>
is more complicated than the other operations.<br>
**NB**<br>
Not all matrices can be multiplied together.

In [ ]:
C = A * B

This is the rule to calculate the matrix dot product:<br>
The number of columns(n) in the first matrix (A) must equal<br>
the number of rows(m) in the second matrix (B).

For example, if matrix A has the dimensions $m$ rows and $n$ columns<br>
and matrix B has the dimensions $n$ and $k$.<br>
The $n$ columns in A and $n$ rows in B are equal, resulting in a new matrix<br>
with $m$ rows and $k$ columns.

In [ ]:
# Matrix dot product
C(m,k) = A(m,n) * B(n,k)

The rule is there because we're calculating the dot product between each row in matrix A<br>
with each column in matrix B.

The matrix multiplication can be implemented in NumPy using the dot() function, shown below.

In [19]:
# matrix dot product
A = array([[1, 2], [3, 4], [5, 6]])
print(f'First matrix, A: \n{A}')
B = array([[1, 2], [3, 4]])
print(f'Second matrix, B: \n{B}')
C = A.dot(B)
print(f'The dot product of A and B: \n{C}')

First matrix, A: 
[[1 2]
 [3 4]
 [5 6]]
Second matrix, B: 
[[1 2]
 [3 4]]
The dot product of A and B: 
[[ 7 10]
 [15 22]
 [23 34]]


A simpler example:

## References

1. [A Gentle Introduction to Linear Algebra](https://machinelearningmastery.com/gentle-introduction-linear-algebra/)<br>
2. [The dot product of two vectors using numpy](https://www.statology.org/numpy-dot-product/#:~:text=How%20to%20Calculate%20Dot%20Product%20Using%20NumPy%20Given,%C2%B7%20b%20%3D%208%20%2B%2015%20%2B%2012)